#pragma once
#include "CoreMinimal.h"
#include "EMAIEmoteType.generated.h"

UENUM(BlueprintType)
enum class EMAIEmoteType : uint8 {
    None,
    Alert,
    CombatSongReaction,
    Taunt,
    Idle,
    Laze,
    Creep,
    UnawareToCurious,
    TransitionToAggro,
    CallReinforcements,
    ChitChat,
    Eat,
    Salute,
    Cower,
    Drink,
    Yawn,
    Guard,
    Cook,
    Pickup,
    Repair,
    Captive,
    Mine,
    ActivityPointsGained,
    Recycle,
    Research,
    Beckon,
    Celebrate,
    Lost,
    EnterMonument,
    Chisel,
    Loiter,
    Bored,
    Admire,
    Guard_2HAxe,
    Guard_2HSword,
    Guard_Axe,
    Guard_Spear,
    Guard_Bow,
    Guard_Crossbow,
    Repair_Low,
    FillKeg_LiftUp,
    FillKeg_LiftDown,
    Relax,
    Socialize,
    Frustrated,
    Hungry,
    LoiterBalust,
    LoiterShelf,
    LoiterHearth,
    LoiterFloor,
    LoiterCounter,
    FillMug,
};

