#!/usr/bin/env python3
"""
Mesh Import Pipeline -- UModel -> glTF -> Blender -> FBX -> UE4

Phase 1: UModel exports all StaticMesh + SkeletalMesh from game paks as glTF
Phase 2: Blender headless batch-converts glTF -> FBX
Phase 3: UE4 Editor imports FBX files into the project

Usage:
    python mesh_import.py --phase 1              # Export meshes via UModel
    python mesh_import.py --phase 2              # Convert glTF -> FBX via Blender
    python mesh_import.py --phase 3              # Import FBX into UE4 project
    python mesh_import.py --phase all            # Run all phases
    python mesh_import.py --status               # Show current state
    python mesh_import.py --phase 1 --dry-run    # Preview without executing
"""

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path, PureWindowsPath

# -- Paths -------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).parent
REPO_ROOT = SCRIPT_DIR.parent
GAME_PAKS = Path(r"C:\Program Files\Epic Games\ReturnToMoria\Moria\Content\Paks")
UMODEL = REPO_ROOT / "tools" / "umodel" / "umodel_64.exe"
BLENDER = Path(r"C:\Program Files\Blender Foundation\Blender 5.0\blender.exe")
BLENDER_SCRIPT = SCRIPT_DIR / "blender_gltf_to_fbx.py"
GLTF_EXPORT_DIR = REPO_ROOT / "tools" / "umodel-meshes-gltf"
FBX_DIR = REPO_ROOT / "tools" / "umodel-meshes-fbx"
CONTENT_DIR = REPO_ROOT / "project" / "Content"
EXTRACTED_ASSETS = REPO_ROOT / "tools" / "extracted-assets" / "Moria" / "Content"
UPROJECT = REPO_ROOT / "project" / "Moria.uproject"
UE4_CMD = Path(r"C:\Program Files\Epic Games\UE_4.27\Engine\Binaries\Win64\UE4Editor-Cmd.exe")
LOG_FILE = REPO_ROOT / "tools" / "mesh-import-log.json"


def _fast_find(directory: Path, extension: str = ".gltf") -> list:
    """Fast recursive file listing via PowerShell (OneDrive-friendly)."""
    dir_str = str(directory).replace("/", "\\")
    try:
        ps_cmd = (
            f"Get-ChildItem -Path '{dir_str}' -Filter '*{extension}' "
            f"-Recurse -File | ForEach-Object {{ $_.FullName }}"
        )
        result = subprocess.run(
            ["powershell", "-NoProfile", "-Command", ps_cmd],
            capture_output=True, text=True, errors="replace", timeout=300
        )
        if result.returncode == 0 and result.stdout.strip():
            return [Path(p) for p in result.stdout.strip().splitlines()]
    except Exception as e:
        print(f"  PowerShell find failed ({e}), falling back to os.walk")
    # Fallback
    found = []
    for root, _, files in os.walk(directory):
        for f in files:
            if f.endswith(extension):
                found.append(Path(root) / f)
    return found


def _count_mesh_assets():
    """Count SM_ and SK_ assets in extracted-assets (what exists in game)."""
    sm = 0
    sk = 0
    for root, _, files in os.walk(EXTRACTED_ASSETS):
        for f in files:
            if f.startswith("SM_") and f.endswith(".uasset"):
                sm += 1
            elif f.startswith("SK_") and f.endswith(".uasset"):
                sk += 1
    return sm, sk


# =============================================================================
# Phase 1: UModel export all meshes as glTF
# =============================================================================
MESH_LIST_FILE = REPO_ROOT / "tools" / "mesh-asset-list.txt"
UMODEL_BATCH_SIZE = 100  # meshes per UModel invocation


def _load_mesh_list():
    """Load the mesh asset path list."""
    if not MESH_LIST_FILE.exists():
        print(f"Mesh list not found, generating...")
        subprocess.run(
            [sys.executable, str(SCRIPT_DIR / "gen_mesh_list.py")],
            cwd=str(REPO_ROOT), check=True
        )
    with open(MESH_LIST_FILE, "r") as f:
        return [l.strip() for l in f if l.strip()]


def phase1_umodel_export(dry_run=False):
    """Export all StaticMesh and SkeletalMesh from game paks via UModel."""
    print("=" * 70)
    print("PHASE 1: UModel Export (paks -> glTF)")
    print("=" * 70)

    if not UMODEL.exists():
        print(f"ERROR: UModel not found at {UMODEL}")
        return False

    if not GAME_PAKS.exists():
        print(f"ERROR: Game paks not found at {GAME_PAKS}")
        return False

    GLTF_EXPORT_DIR.mkdir(parents=True, exist_ok=True)

    # Load mesh asset list (generated by gen_mesh_list.py)
    mesh_paths = _load_mesh_list()
    print(f"Total mesh assets in game: {len(mesh_paths)}")

    # Check which are already exported
    to_export = []
    already_done = 0
    for mp in mesh_paths:
        gltf_path = GLTF_EXPORT_DIR / "Game" / (mp + ".gltf")
        if gltf_path.exists():
            already_done += 1
        else:
            to_export.append(mp)

    print(f"  Already exported: {already_done}")
    print(f"  To export: {len(to_export)}")
    print(f"  Output dir: {GLTF_EXPORT_DIR}")

    if dry_run:
        print(f"\n[DRY RUN] Would export {len(to_export)} meshes in batches of {UMODEL_BATCH_SIZE}")
        return True

    if not to_export:
        print("All meshes already exported!")
        return True

    # Process in batches -- UModel takes one primary package + multiple -pkg= args
    total_batches = (len(to_export) + UMODEL_BATCH_SIZE - 1) // UMODEL_BATCH_SIZE
    total_exported = 0
    total_errors = 0
    log_path = REPO_ROOT / "tools" / "umodel-export.log"

    with open(log_path, "w") as master_log:
        for batch_idx in range(total_batches):
            start = batch_idx * UMODEL_BATCH_SIZE
            end = min(start + UMODEL_BATCH_SIZE, len(to_export))
            batch = to_export[start:end]

            # First mesh is the primary package, rest are -pkg= args
            cmd = [
                str(UMODEL),
                "-game=ue4.27",
                f"-path={GAME_PAKS}",
                "-export",
                "-gltf",
                "-notex",
                "-nooverwrite",
                f"-out={GLTF_EXPORT_DIR}",
            ]
            # Add extra packages
            for extra in batch[1:]:
                cmd.append(f"-pkg={extra}")
            # Primary package last
            cmd.append(batch[0])

            t0 = time.time()
            print(f"\nBatch {batch_idx + 1}/{total_batches} ({len(batch)} meshes)...", flush=True)

            try:
                proc = subprocess.Popen(
                    cmd,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    text=True,
                    errors="replace",
                    bufsize=1
                )
                exported = 0
                errors = 0
                for line in proc.stdout:
                    master_log.write(line)
                    if line.startswith("Exporting StaticMesh") or line.startswith("Exporting SkeletalMesh"):
                        exported += 1
                    elif "ERROR" in line:
                        errors += 1
                        if total_errors + errors <= 20:
                            print(f"  ERROR: {line.strip()}", flush=True)

                proc.wait()
                elapsed = time.time() - t0
                total_exported += exported
                total_errors += errors
                print(f"  {exported} meshes exported in {elapsed:.1f}s (errors: {errors})", flush=True)

            except Exception as e:
                print(f"  EXCEPTION: {e}", flush=True)
                total_errors += len(batch)

    print(f"\n{'=' * 70}")
    print(f"UModel export complete.")
    print(f"  Meshes exported: {total_exported}")
    print(f"  Errors: {total_errors}")
    print(f"  Log: {log_path}")

    # Count actual glTF files produced
    gltf_files = _fast_find(GLTF_EXPORT_DIR, ".gltf")
    print(f"  glTF files on disk: {len(gltf_files)}")

    return total_exported > 0


# =============================================================================
# Phase 2: Blender batch convert glTF -> FBX
# =============================================================================
def phase2_blender_convert(dry_run=False, batch_size=50):
    """Convert all glTF files to FBX via Blender headless."""
    print("=" * 70)
    print("PHASE 2: Blender Convert (glTF -> FBX)")
    print("=" * 70)

    if not BLENDER.exists():
        print(f"ERROR: Blender not found at {BLENDER}")
        return False

    if not BLENDER_SCRIPT.exists():
        print(f"ERROR: Blender script not found at {BLENDER_SCRIPT}")
        return False

    # Find all glTF files
    gltf_files = _fast_find(GLTF_EXPORT_DIR, ".gltf")
    print(f"Found {len(gltf_files)} glTF files")

    if not gltf_files:
        print("No glTF files to convert. Run Phase 1 first.")
        return False

    FBX_DIR.mkdir(parents=True, exist_ok=True)

    # Determine which ones still need conversion
    to_convert = []
    already_done = 0
    for gltf_path in gltf_files:
        # Mirror directory structure from gltf export to fbx dir
        rel = gltf_path.relative_to(GLTF_EXPORT_DIR)
        fbx_path = FBX_DIR / rel.with_suffix(".fbx")
        if fbx_path.exists():
            already_done += 1
        else:
            to_convert.append((gltf_path, fbx_path))

    print(f"  Already converted: {already_done}")
    print(f"  To convert: {len(to_convert)}")

    if dry_run:
        print(f"\n[DRY RUN] Would convert {len(to_convert)} files")
        return True

    if not to_convert:
        print("All files already converted!")
        return True

    # Write a batch Blender script that processes multiple files per launch
    # (launching Blender per-file is slow due to startup overhead)
    batch_script = SCRIPT_DIR / "blender_batch_gltf_to_fbx.py"
    batch_script_content = '''"""Blender batch script: convert multiple glTF files to FBX.
Usage: blender --background --python this_script.py -- manifest.json
"""
import sys
import json
import os
import bpy

argv = sys.argv[sys.argv.index("--") + 1:]
manifest_path = argv[0]

with open(manifest_path, "r") as f:
    pairs = json.load(f)

total = len(pairs)
for i, (gltf_in, fbx_out) in enumerate(pairs, 1):
    try:
        # Reset scene
        bpy.ops.wm.read_homefile(use_empty=True)

        # Import glTF
        bpy.ops.import_scene.gltf(filepath=gltf_in)

        # Ensure output directory exists
        os.makedirs(os.path.dirname(fbx_out), exist_ok=True)

        # Export FBX -- UE4-compatible settings
        bpy.ops.export_scene.fbx(
            filepath=fbx_out,
            axis_forward='-Z',
            axis_up='Y',
            use_selection=False,
            global_scale=1.0,
            apply_unit_scale=True,
            apply_scale_options='FBX_SCALE_ALL',
            mesh_smooth_type='FACE',
            add_leaf_bones=False,
        )

        if i % 25 == 0 or i == total:
            print(f"PROGRESS: {i}/{total} converted", flush=True)

    except Exception as e:
        print(f"ERROR converting {gltf_in}: {e}", flush=True)

print(f"BATCH COMPLETE: {total} files processed")
'''
    with open(batch_script, "w") as f:
        f.write(batch_script_content)

    # Process in batches to avoid memory issues
    converted = 0
    errors = 0
    total_batches = (len(to_convert) + batch_size - 1) // batch_size

    for batch_idx in range(total_batches):
        start = batch_idx * batch_size
        end = min(start + batch_size, len(to_convert))
        batch = to_convert[start:end]

        print(f"\nBatch {batch_idx + 1}/{total_batches} ({len(batch)} files)...")

        # Write manifest
        manifest_path = REPO_ROOT / "tools" / "blender-manifest.json"
        pairs = [[str(g), str(f)] for g, f in batch]
        with open(manifest_path, "w") as mf:
            json.dump(pairs, mf)

        cmd = [
            str(BLENDER),
            "--background",
            "--python", str(batch_script),
            "--", str(manifest_path)
        ]

        t0 = time.time()
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            errors="replace",
            timeout=600  # 10 min per batch
        )
        elapsed = time.time() - t0

        # Count results
        batch_converted = 0
        for _, fbx_path in batch:
            if fbx_path.exists():
                batch_converted += 1
        batch_errors = len(batch) - batch_converted

        converted += batch_converted
        errors += batch_errors
        print(f"  Done in {elapsed:.1f}s -- {batch_converted} converted, {batch_errors} errors")

        if proc.returncode != 0 and batch_errors == len(batch):
            print(f"  WARNING: Blender exited with code {proc.returncode}")
            # Print last few lines of output for debugging
            for line in (proc.stdout or "").splitlines()[-5:]:
                print(f"    {line}")

    print(f"\n{'=' * 70}")
    print(f"Blender conversion complete.")
    print(f"  Converted: {converted}")
    print(f"  Errors: {errors}")
    print(f"  Total FBX files: {converted + already_done}")

    return errors == 0


# =============================================================================
# Phase 3: Import FBX into UE4 project
# =============================================================================
def phase3_ue4_import(dry_run=False, batch_size=100):
    """Import FBX files into UE4 via Editor commandlet.

    Groups FBX files by destination directory, then imports each group
    with a single UE4 editor launch per group.

    To minimize editor launches (each takes ~30-60s startup), we batch
    multiple destination directories into a single ImportAssets call
    by mirroring the directory structure under a temp source folder.
    """
    print("=" * 70)
    print("PHASE 3: UE4 FBX Import")
    print("=" * 70)

    if not UE4_CMD.exists():
        print(f"ERROR: UE4 Editor not found at {UE4_CMD}")
        return False

    # Find all FBX files
    fbx_files = _fast_find(FBX_DIR, ".fbx")
    print(f"Found {len(fbx_files)} FBX files")

    if not fbx_files:
        print("No FBX files to import. Run Phase 2 first.")
        return False

    # Check which are already imported
    to_import = []
    already_done = 0
    for fbx_path in fbx_files:
        rel = fbx_path.relative_to(FBX_DIR)
        parts = list(rel.parts)
        if parts[0] == "Game":
            parts = parts[1:]
        uasset_rel = Path(*parts).with_suffix(".uasset")
        uasset_path = CONTENT_DIR / uasset_rel

        if uasset_path.exists():
            already_done += 1
        else:
            # Store: (fbx_path, relative_content_path_with_fbx_name)
            to_import.append((fbx_path, Path(*parts)))

    print(f"  Already imported: {already_done}")
    print(f"  To import: {len(to_import)}")

    if dry_run:
        print(f"\n[DRY RUN] Would import {len(to_import)} FBX files")
        for fbx, rel in to_import[:10]:
            dest = "/Game/" + str(rel.parent).replace("\\", "/")
            print(f"  {fbx.name} -> {dest}")
        if len(to_import) > 10:
            print(f"  ... and {len(to_import) - 10} more")
        return True

    if not to_import:
        print("All meshes already imported!")
        return True

    # Strategy: Group by destination directory, import one dir at a time.
    # Each ImportAssets call: -source=<temp_dir> -dest=/Game/<path>
    by_dest = {}
    for fbx_path, rel_path in to_import:
        dest = "/Game/" + str(rel_path.parent).replace("\\", "/")
        if dest not in by_dest:
            by_dest[dest] = []
        by_dest[dest].append(fbx_path)

    print(f"  Unique destination dirs: {len(by_dest)}")

    imported = 0
    errors = 0
    dir_count = 0
    total_dirs = len(by_dest)
    import shutil

    for dest_path, fbx_list in sorted(by_dest.items()):
        dir_count += 1

        # Create temp directory with just these FBX files
        temp_dir = REPO_ROOT / "tools" / "fbx-import-temp"
        if temp_dir.exists():
            shutil.rmtree(temp_dir, ignore_errors=True)
        temp_dir.mkdir(parents=True, exist_ok=True)

        for fbx in fbx_list:
            shutil.copy2(fbx, temp_dir / fbx.name)

        cmd = [
            str(UE4_CMD),
            str(UPROJECT),
            "-run=ImportAssets",
            f"-source={temp_dir}",
            f"-dest={dest_path}",
            "-nosourcecontrol",
            "-nullrhi",
            "-log",
        ]

        log_path = REPO_ROOT / "tools" / f"fbx-import-dir-{dir_count}.log"
        t0 = time.time()

        print(f"\n[{dir_count}/{total_dirs}] {dest_path} ({len(fbx_list)} files)...", flush=True)

        try:
            with open(log_path, "w") as log_f:
                proc = subprocess.run(
                    cmd,
                    stdout=log_f,
                    stderr=subprocess.STDOUT,
                    timeout=600,  # 10 min per directory
                )
            elapsed = time.time() - t0

            # Count successful imports
            dir_imported = 0
            for fbx in fbx_list:
                rel = fbx.relative_to(FBX_DIR)
                parts = list(rel.parts)
                if parts[0] == "Game":
                    parts = parts[1:]
                check_path = CONTENT_DIR / Path(*parts).with_suffix(".uasset")
                if check_path.exists():
                    dir_imported += 1

            dir_errors = len(fbx_list) - dir_imported
            imported += dir_imported
            errors += dir_errors

            status = "OK" if dir_errors == 0 else f"{dir_errors} FAILED"
            print(f"  {dir_imported}/{len(fbx_list)} imported ({elapsed:.1f}s) [{status}]", flush=True)

        except subprocess.TimeoutExpired:
            print(f"  TIMEOUT", flush=True)
            errors += len(fbx_list)
        except Exception as e:
            print(f"  ERROR: {e}", flush=True)
            errors += len(fbx_list)

    # Cleanup temp
    temp_dir = REPO_ROOT / "tools" / "fbx-import-temp"
    if temp_dir.exists():
        shutil.rmtree(temp_dir, ignore_errors=True)

    print(f"\n{'=' * 70}")
    print(f"UE4 import complete.")
    print(f"  Imported: {imported}")
    print(f"  Errors: {errors}")
    print(f"  Total mesh assets in project: {imported + already_done}")

    return errors == 0


# =============================================================================
# Status
# =============================================================================
def show_status():
    """Show current state of mesh import pipeline."""
    print("=" * 70)
    print("MESH IMPORT PIPELINE -- STATUS")
    print("=" * 70)

    # Game paks
    print(f"\nGame paks: {GAME_PAKS}")
    if GAME_PAKS.exists():
        pak_files = list(GAME_PAKS.glob("*"))
        for p in pak_files:
            size_mb = p.stat().st_size / (1024 * 1024)
            print(f"  {p.name}: {size_mb:.1f} MB")
    else:
        print("  NOT FOUND")

    # UModel
    print(f"\nUModel: {UMODEL}")
    print(f"  {'EXISTS' if UMODEL.exists() else 'NOT FOUND'}")

    # Blender
    print(f"\nBlender: {BLENDER}")
    print(f"  {'EXISTS' if BLENDER.exists() else 'NOT FOUND'}")

    # Phase 1: glTF exports
    print(f"\nPhase 1 -- glTF exports: {GLTF_EXPORT_DIR}")
    if GLTF_EXPORT_DIR.exists():
        gltf_files = _fast_find(GLTF_EXPORT_DIR, ".gltf")
        print(f"  glTF files: {len(gltf_files)}")
    else:
        print("  Directory not created yet")

    # Phase 2: FBX conversions
    print(f"\nPhase 2 -- FBX files: {FBX_DIR}")
    if FBX_DIR.exists():
        fbx_files = _fast_find(FBX_DIR, ".fbx")
        print(f"  FBX files: {len(fbx_files)}")
    else:
        print("  Directory not created yet")

    # Phase 3: UE4 imports
    print(f"\nPhase 3 -- UE4 project: {CONTENT_DIR}")
    # Count mesh .uasset files in project
    mesh_count = 0
    sm_count = 0
    sk_count = 0
    if CONTENT_DIR.exists():
        for root, _, files in os.walk(CONTENT_DIR):
            for f in files:
                if f.endswith(".uasset"):
                    if f.startswith("SM_"):
                        sm_count += 1
                        mesh_count += 1
                    elif f.startswith("SK_"):
                        sk_count += 1
                        mesh_count += 1
        print(f"  StaticMesh (SM_): {sm_count}")
        print(f"  SkeletalMesh (SK_): {sk_count}")
        print(f"  Total meshes in project: {mesh_count}")

    # Game totals for comparison
    print(f"\nGame reference (extracted-assets):")
    try:
        ps_sm = subprocess.run(
            ["powershell", "-NoProfile", "-Command",
             f"(Get-ChildItem '{EXTRACTED_ASSETS}' -Filter 'SM_*.uasset' -Recurse -File).Count"],
            capture_output=True, text=True, timeout=60
        )
        ps_sk = subprocess.run(
            ["powershell", "-NoProfile", "-Command",
             f"(Get-ChildItem '{EXTRACTED_ASSETS}' -Filter 'SK_*.uasset' -Recurse -File).Count"],
            capture_output=True, text=True, timeout=60
        )
        game_sm = int(ps_sm.stdout.strip()) if ps_sm.stdout.strip() else 0
        game_sk = int(ps_sk.stdout.strip()) if ps_sk.stdout.strip() else 0
        print(f"  StaticMesh (SM_): {game_sm}")
        print(f"  SkeletalMesh (SK_): {game_sk}")
        print(f"  Total game meshes: {game_sm + game_sk}")
        if mesh_count > 0:
            pct = mesh_count / (game_sm + game_sk) * 100 if (game_sm + game_sk) > 0 else 0
            print(f"  Coverage: {pct:.1f}%")
    except Exception:
        print("  (Could not count)")

    print()


# =============================================================================
# Main
# =============================================================================
def main():
    parser = argparse.ArgumentParser(description="Mesh Import Pipeline")
    parser.add_argument("--phase", choices=["1", "2", "3", "all"], help="Which phase to run")
    parser.add_argument("--status", action="store_true", help="Show current status")
    parser.add_argument("--dry-run", action="store_true", help="Preview without executing")
    parser.add_argument("--batch-size", type=int, default=50, help="Blender/UE4 batch size")
    args = parser.parse_args()

    if args.status or not args.phase:
        show_status()
        if not args.phase:
            return

    if args.phase in ("1", "all"):
        ok = phase1_umodel_export(dry_run=args.dry_run)
        if not ok and args.phase == "all":
            print("Phase 1 had issues. Continuing anyway...")

    if args.phase in ("2", "all"):
        ok = phase2_blender_convert(dry_run=args.dry_run, batch_size=args.batch_size)
        if not ok and args.phase == "all":
            print("Phase 2 had issues. Continuing anyway...")

    if args.phase in ("3", "all"):
        ok = phase3_ue4_import(dry_run=args.dry_run, batch_size=args.batch_size)


if __name__ == "__main__":
    main()
